version: '3.7'

#setta alcune variabili d'ambiente
x-common-variables: &mongo-variables
  - MONGO_INITDB_DATABASE=animal_db
  - MONGO_INITDB_ROOT_USERNAME=root
  - MONGO_INITDB_ROOT_PASSWORD=pass

services:
  client:
      build:
        dockerfile: Dockerfile
        context: ./frontend
      volumes:
        #In questo modo dico a docker di usare la cartella del container /app/node_modules come volume
        #La cartella locale node_modules (se non ha modifiche) non verrà più copiata perchè il volume esiste già
        #Se c'è già l'immagine docker-compose non la builda
        - /app/node_modules 
        #Qui mappa tutto il contenuto della cartella locale client nella cartella app dell'immagine
        #Ricorda che la WORKDIR dell'immagine è la cartella app
        - ./frontend:/app
      ports:
        - 80:80
      networks:
      - shared-network
  server:
      build:
        dockerfile: Dockerfile
        context: ./backend
      volumes:
        - ./backend:/app
      ports:
        - 5000:5000
      networks:
      - shared-network

networks:
  shared-network:

